### PR TITLE
Add more documentation, i.e. about null and this keywords

### PR DESCRIPTION
**Pull request by XomaDev**
I've added more documentation to the Logic section.
I was not really totally sure how I could add images and other things.

### CODE REVIEW

**Comment by XomaDev** [comment]
I've updated the docs, let me know if there is something to change 😊

**Review by MohamedTamer94 — CHANGES_REQUESTED** [review]
Looks nice! There seem to be some arbitrary IDE-generated files that were pushed as well. Would you mind deleting them before we merge it?

**Comment by XomaDev** [comment]
> Looks nice! There seem to be some arbitrary IDE-generated files that were pushed as well. Would you mind deleting them before we merge it?

I've cleared them now, I had not noticed that they were added.

**Review by MohamedTamer94 — APPROVED** [review]
LGTM

**Pull request merged**
